type Price {
    currency: Currency!,
    amount: Float!
}

type Attribute {
    displayValue: String,
    value: String,
    id: String!
}

type AttributeSet {
    id: String!,
    name: String,
    type: String,
    items: [Attribute]
}

type Product {
    _id: String!,
    setId: String!,
    name: String!,
    inStock: Boolean,
    gallery: [String],
    description: String!,
    category: String!,
    attributes: [AttributeSet]
    prices: [Price!]!,
    brand: String!
}

type Category {
    name: String,
    products: [Product]!
}

type Currency {
    label: String!,
    symbol: String!
}

type Query {
    getCategories: [Category],
    getCategory(input: CategoryInput): Category,
    getProduct(setId: String!): Product,
    getCurrencies: [Currency]
}

input CategoryInput {
    title: String!
}

type Mutation {
    postProducts(input: ProductInput!): Product,
}

input ProductInput {
    setId: String!,
    name: String!,
    inStock: Boolean,
    gallery: String,
    description: String!,
    category: String!,
    attributes: String
    prices: String,
    brand: String!
}